### ISSUE TITLE
Gulp 4.0 support?

### ISSUE THREAD

**Issue by phated** [niki4810/gulp-devtools#12]
We are getting very close to releasing gulp 4.0 with a new API.  Are there any plans to support 4.0?

You might find the [`gulp.tree()`](https://github.com/phated/undertaker#treeoptions--object) API helpful for getting tasks that have been registered.

I bring this up due to an outstanding issue we have open at https://github.com/gulpjs/gulp/issues/365

**Comment by niki4810** [comment]
@phated  Sorry for the delayed response. I will plan on updating it soon. Will keep you posted.
