### ISSUE TITLE
Unable to successfully use with Chrome 35 and 36

### ISSUE THREAD

**Issue by addyosmani** [niki4810/gulp-devtools#2]
I've been testing this project against the output of [generator-gulp-webapp](https://github.com/yeoman/generator-gulp-webapp) (a valid Gulp project) with the recommended one-line changes made to my Gulpfile.

Unfortunately, even with a fresh project following the steps in the readme I wasn't able to get Gulp DevTools successfully connecting up to my project once `gulp-devtools` was run. This was with Chrome Beta and Chrome Canary. Does this extension currently work in these versions of Chrome?

**Comment by niki4810** [comment]
Hi @addyosmani! , Firstly an honor to meet you here :) . I just tested on latest chrome canary and chrome-beta (v 35) the tasks appear to run correctly. 

chrome-beta (v 35)
![chrome-beta](https://cloud.githubusercontent.com/assets/1467801/2938790/67987db0-d922-11e3-81ac-d03c1eed9d4f.gif)
chrome-canary (v 37)
![chrome-canary-demo](https://cloud.githubusercontent.com/assets/1467801/2938791/67a844fc-d922-11e3-869a-cf1b7c10f92c.gif)

Currently, I am using port `8001`, for communicating between the plugin and extension. Do you have anything running on this port ? If you have anything running, could you please stop it and re-run gulp-devtools plugin.

**Comment by addyosmani** [comment]
Great meeting you on here too! :) Thanks for re-checking @niki4810. I just reset anything running on  the default port for the extension and everything seems to be working fine now. Cheers!
