### ISSUE TITLE
Remove node-gyp

### ISSUE THREAD

**Issue by adam-lynch** [niki4810/gulp-devtools#3]
Is there any chance this dependency could be removed? node-gyp can be a pain for Windows users. I've had it a lot in the past. 

For example, the errors gotten when trying to install install project just now:

> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
> MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to 
> the system path if it is installed elsewhere.  [C:\Users\Adam\AppData\Roaming\npm\node_modules\gulp-devtools\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\binding.sln]
> MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to 
> the system path if it is installed elsewhere.  [C:\Users\Adam\AppData\Roaming\npm\node_modules\gulp-devtools\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\binding.sln]

**Comment by adam-lynch** [comment]
I understand it must be the dependency of a dependency, but stilll, it would be great :)

**Comment by niki4810** [comment]
@adam-lynch : did you get this error when running `npm install gulp-devtools -g` ?
I don't have a solution for this as of now. I have have to work on it. I am new to node, so if you have any suggestions I am open to working with you on this :)

**Comment by adam-lynch** [comment]
@niki4810 Yeah. 

No solution. I've had to deal with this in the past by following steps in the error messages, googling around, etc. but each time there's another error and another. I did get node-gyp working once on one machine but after a good bit of hassle. I just avoid a project depending on it nowdays.

I'm no node expert either, but what I think we could try do is find which of gulp-devtools' dependent modules themselves depend on node-gyp (eventually down the chain) and then use a different module instead; i.e. replacing mime with something similar, if that was the one which depended on it. If that's even possible with the problematic module in question.

**Comment by niki4810** [comment]
@adam-lynch : Hmm, ok, Thanks for reporting this. I will look into it.

**Comment by stramel** [comment]
@adam-lynch @niki4810 The package that is causing this issue is `socket.io`. Having the Microsoft Visual Studio C++ (2010 or 2012) (Standard or Express) will fix these issues with node-gyp. If you decide to go with 2012 you may have to install with the `--msvs_version=2012` flag. (`npm install --msvs_version=2012 <package>`)

I would close this issue.

**Comment by niki4810** [comment]
@stramel Thanks!

**Comment by niki4810** [comment]
I will update docs with this fix.
