### ISSUE TITLE
gulp-devtools throws error no matter what Gulp task I try and run

### ISSUE THREAD

**Issue by u01jmg3** [niki4810/gulp-devtools#5]
I keep getting an error when I try and run any of my Gulp tasks through `gulp-devtools` in Chrome (`v35.0.1916.153`):

```
C:\Program Files\WAMP Server 2\www\gulp-starter>gulp-devtools
Gulp Tasks loaded, fire up your chrome devtools
   info  - socket.io started
Running Task:stats

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```

And here is my task:

``` js
gulp.task('stats', function(){
    return gulp.src(srcJs)
        .pipe($.complexity())
    ;
});
```

Any ideas what I'm doing wrong?

**Comment by niki4810** [comment]
@u01jmg3 hard to tell. can you check if you  `gulp` command work from terminal ? This will help me understand there is no fault with your gulp tasks.

**Comment by u01jmg3** [comment]
Yep task works flawlessly with `gulp` in the command line. I tried other working `gulp` tasks with your Chrome plugin and I get the same error. Not quite sure what's going wrong.

**Comment by niki4810** [comment]
@u01jmg3 not sure what $.complexity() does, can you provide me an gist for your gulpfile.js so that i can try locally.

**Comment by u01jmg3** [comment]
`$.complexity()` is just [`gulp-complexity`](https://www.npmjs.org/package/gulp-complexity) - it's a task I chose at random from my `gulpfile.js`

I'm calling it using `var $ = require('gulp-load-plugins')()` - see [`gulp-load-plugins`](https://www.npmjs.org/package/gulp-load-plugins)

I can provide you a gist if what I've said above still doesn't make things clear

Thanks for your time

**Comment by niki4810** [comment]
@u01jmg3  makes sense, let me investigate and get back to you.

**Comment by niki4810** [comment]
@u01jmg3 Sorry for the delay in getting back to this issue. I did a little test on this issue and things work fine for me. See the image gif below 

![gulp-issue-4-test](https://cloud.githubusercontent.com/assets/1467801/3661746/ca6f00ce-11c3-11e4-8b81-5b0eafbcd937.gif)

Here is a sample gist with my `package.json` , `gulpfile.js` and a `sample.js` file : https://gist.github.com/niki4810/0b2b5ada5c0c76dfe930

The issue you are hitting might be local.

**Comment by u01jmg3** [comment]
No problem on the delay

I've setup your gist on my work machine and I am still seeing the same problem - see the gif below

![issue-5](https://cloud.githubusercontent.com/assets/1266205/3671321/7dec127e-124e-11e4-878d-13f54efae005.gif)

Any ideas what could be affecting things locally for me? I've tried both on my work PC and my own laptop. I thought WAMP was perhaps interfering but it's not running. I use `browser-sync` (thinking of another plugin which runs in a similar way to `gulp-devtools`) with no issues. Open to suggestions - appreciate your help

**Comment by niki4810** [comment]
@u01jmg3  ok, I was under assumption you were using a mac :) . My guess is that when spwaning the gulp command I should do something like (process.platform === 'win32') ? 'gulp.cmd' : 'gulp'; I never tested it on a PC.  Will work on it an let you know.  Thanks for reporting this.

**Comment by stramel** [comment]
Having the same issue on Windows 7.

**Comment by niki4810** [comment]
@stramel I will look into this issue over the weekend. Will post my update on this thread.

**Comment by stramel** [comment]
Looks like using `child_process.exec` would possibly fix this issue?

**Comment by niki4810** [comment]
@u01jmg3  / @stramel  , alternative if you could try this locally it would be helpful. I dont have a PC so have to install windows on my MAC (:() to test this out .

basically my guess is (not 100% sure), this line : https://github.com/niki4810/gulp-devtools/blob/master/lib/gulp-devtools.js#L80 needs to change 

from : 

```
var worker = spawn('gulp', [data.taskName]);
```

to : 

```
 var spawnCmd = (process.platform === 'win32') ? 'gulp.cmd' : 'gulp';
 var worker = spawn(spawnCmd, [data.taskName]);
```

If either of you can try it out locally that would be great.

**Comment by niki4810** [comment]
@stramel  Great, I am no Node expert :), but if its fixed PR is always welcome

**Comment by niki4810** [comment]
@stramel  I dont think we could used `exec`, the reason I used spawn is to allow gulp tasks to run in background. Does that break with using `exec` ??

**Comment by stramel** [comment]
@niki4810 Let me test running it in the background

**Comment by stramel** [comment]
@niki4810 `exec` does break the Run in Background feature as it doesn't have the `detach` option. Although, it looks like someone has requested `exec` to expose the `detach` option. [link](https://github.com/joyent/node/issues/7960)

I will give your code snippet a shot and see if that fixes it for the time being.

**Comment by niki4810** [comment]
Could you please try my solution in the above comment too ?

**Comment by stramel** [comment]
@niki4810 Your suggested solution does work. Although, if the `detach` option does get added to `exec`, it may be worth switching to it. Thanks for staying on top of this!

**Comment by niki4810** [comment]
@stramel Thanks a lot of helping me debug this issue. I will open a PR with My fix. As you suggested will plan switching to exec, once https://github.com/joyent/node/issues/7960 gets resolved.

**Comment by u01jmg3** [comment]
Great stuff - I'll await an update to `gulp-devtools` with a fix

**Comment by niki4810** [comment]
@u01jmg3 I have check in the fix. Please run 
- `sudo npm uninstall -g gulp-devtools` 
- `npm cache clear`  (optional)
- `sudo npm install -g gulp-devtools`

**Comment by u01jmg3** [comment]
I can confirm things are now working for me! Thanks @niki4810, @stramel

(By the way, no `sudo` on Windows and I didn't have to clear my cache)

**Comment by niki4810** [comment]
Thanks @u01jmg3
