### ISSUE TITLE
Updating Dependencies

### ISSUE THREAD

**Issue by stramel** [niki4810/gulp-devtools#7]
May be good to update the dependencies, not a big issue. Just good to keep them up-to-date. 
- socket.io can be updated from ~0.9.16 to ~1.0.6
- gulp can be updated from ~3.6.2 to ~3.8.6
- gulp-jshint can be updated from ~1.5.5 to ~1.8.0
- jshint-stylish can be updated from ~0.2.0 to ~0.4.0

**Comment by niki4810** [comment]
Updated `gulp`, `gulp-jshint`, `jshint-stylish`. `socked.io` seems to be a major upgrade, need to do some work on it.

**Comment by stramel** [comment]
Thanks! Perhaps tag using semver once `socket.io` is updated.
