### ISSUE TITLE
gulp task in different file is not working

### ISSUE THREAD

**Issue by sadhasivam** [niki4810/gulp-devtools#8]
we have a modularized gulp task residing in various smaller unit of files.  

Line: 13 var gulpFilePath = path.join(process.cwd(), "gulpfile"); may not have all tasks to fetch.  
so gulp-devtools is failing for this instance. any thoughts on this would be help-full.

**Comment by niki4810** [comment]
@sadhasivam can you give me some more info, hard to figure what you are tying to say. could you create a gist for your scenario and share it. :)

**Comment by sadhasivam** [comment]
Thanks. we adapted our Gulp Structure something like below.  if i use dev-tools where main gulpFile.js resides causing the above problem mentioned.  

https://github.com/greypants/gulp-starter

**Comment by niki4810** [comment]
@sadhasivam  Thanks, will take a look and let you know.

**Comment by sadhasivam** [comment]
sorry about the confusion. gulp-devtools works charm.
